### ISSUE TITLE
Spacing not supported

### ISSUE THREAD

**Issue by pikooh** [excaliburjs/excalibur-tiled#11]
The spacing option in the tileset is not observed when using excalibur-tiled.

**Comment by kamranayub** [comment]
This is interesting. @eonarheim do you think TileMap supports spacing (or would)? Might need to add an enhancement to http://github.com/excaliburjs/excalibur.

**Comment by kamranayub** [comment]
Fixed in https://github.com/excaliburjs/Excalibur/issues/1058
