### ISSUE TITLE
Add support for Tiled objects

### ISSUE THREAD

**Issue by DaVince** [excaliburjs/excalibur-tiled#113]
### Context
I couldn't find a specific issue about it, hence I'm adding one. It's clear that there is intent to support this anyway. 🙂

While it is possible to get the properties out of the map file with some hacking around, by sheer virtue of the maps being loaded as JSON, it makes more sense to be able to make use of the ITiledMapLayer.objects array. It exists, but is never filled with anything.

### Proposal
There is no need for a proposal; the `ITiledMapObject` interface already exists and should be very usable for implementing this.

**Comment by DaVince** [comment]
I just realized that the objects _are_ populated. I just can't figure out how the objects are populated -- something that came for free with the JSON parsing?

In any case, I guess that makes this ticket invalid!

**Comment by kamranayub** [comment]
The tiled plugin essentially just passes all the raw json back as `data` so
everything tiled exports should be available. Like you found, we used
objects in the last game for spawn markers.
