### ISSUE TITLE
Readme example outdated?

### ISSUE THREAD

**Issue by jlbeard84** [excaliburjs/excalibur-tiled#13]
I've tried using excalibur-tiled with both the most recent version (13.1 as of now) as well as 11.0 that is mentioned here in the docs with no luck. Is the example to load a sheet in the readme out of date, or did something else break in the engine? I've been trying everything I could think of to get something loaded to no avail. Any suggestions would be appreciated.

**Comment by bferguson3** [comment]
Seconded, the closest I can get to loading in a Tiled map is by altering the assetPath, but even then it doesn't seem to pull the image from anywhere and insists the spritesheet array is 0x0:
excalibur.js:6019 Uncaught RangeError: Invalid array length

**Comment by kamranayub** [comment]
Have you tried running the sample inside the repo? Is that working?

**Comment by jlbeard84** [comment]
From the sample inside the repo do you mean what is in the test directory? I assumed that was unit tests, but I can certainly run that if it's an example.

And yeah, I'm trying to get it going via webpack-dev-server.

**Comment by kamranayub** [comment]
Yep! It should work, I just tested it:

![image](https://user-images.githubusercontent.com/563819/31839251-e1c106da-b5a5-11e7-858d-27c8fa4fecda.png)

**Comment by kamranayub** [comment]
Another tip, I think newer Tiled likes to export as base64 JSON, don't do that, use regular JSON...

**Comment by bferguson3** [comment]
I got it to build, but here's where I think its failing on my end:
You have one file for the tilemap, when the latest version of Tiled requires both a map and tileset (.tsx/.json) file *as well* as the image in order to render. It seems that the test.json file included in your /test/ has the data from the .tsx file already inside the "tilesets": block. 

What version of Tiled do you use? When did Tiled start using tilesets as seperate files?

**Comment by bferguson3** [comment]
As another note the structure for the .json tileset file that new versions of Tiled outputs looks different than what is in your test.json map file.

**Comment by kamranayub** [comment]
Oh very interesting! I'll have to take a look, when I have a chance I'll send the version I was using, it was probably around the April 2017 timeframe where we last used it.

**Comment by bferguson3** [comment]
Awesome, thanks Kamran ^^

**Comment by kamranayub** [comment]
No **thank you** because now I know what my next live stream will be about ;)

**Comment by bferguson3** [comment]
I can confirm that it works fine with Tiled files created on < v1.0 (like 0.18, pre-May). Thanks for your assistance diagnosing this!

**Comment by jlbeard84** [comment]
Yep! Can also confirm. I think it would probably be helpful to have something in the documentation with regards to the version of Tiled for devs going forward. Thanks for your help!

**Comment by eonarheim** [comment]
@kamranayub would it make sense to support both formats under a flag of somekind?

Perhaps a LEGACY flag to support older tiled files pre v1.0 then by default support the newer format?

**Comment by kamranayub** [comment]
I think I'll be able to detect it automatically. We will find out Thursday
when I work on it. Tune in to help if you like!

**Comment by kamranayub** [comment]
Hi guys, thanks for reporting this issue. I've found the problem! If you don't check "embed in map" when you create a tileset:

![image](https://user-images.githubusercontent.com/563819/32084294-dc0a4016-ba8d-11e7-8862-b099e653e9eb.png)

Then it requires an external file. If you embed it, it will work as it did before.

I will create a new issue for adding support for loading dependent TSX files when not embedded but that's the workaround for now!

**Comment by kamranayub** [comment]
This support should now work out of the box. Thanks for reporting!

**Comment by jlbeard84** [comment]
Thanks for the update!
