### ISSUE TITLE
Include .d.ts files in npm package

### ISSUE THREAD

**Issue by SnareChops** [excaliburjs/excalibur-tiled#17]
This project should include the `.d.ts` typing files with it's output files that are published to npm. This way they can be consumed by other typescript files without compiler errors and constant casting to `any` or manually declaring all types. I can see that building your master branch does this, it just hasn't been published to npm

> Minor note `import TiledResource from 'excalibur-tiled';` should be `import TiledResouce from '@excaliburjs/excalibur-tiled';` in README.md since that is the default import when installing from npm.

**Comment by kamranayub** [comment]
Thanks! Yes, it got missed in the last release. I'll see about getting it
fixed in a patch release.

**Comment by Beng89** [comment]
Can you reopen this issue? The typescript definitions are not being included in the npm package.

Verified against: "version": "2.3.0"

![notypescriptdefinitions](https://user-images.githubusercontent.com/5748243/51086522-75360900-170d-11e9-8537-6636fede9ff2.PNG)

**Comment by eonarheim** [comment]
Hi @Beng89 thanks for bringing this to our attention, we'll investigate an re-open

**Comment by eonarheim** [comment]
@Beng89 I've pushed a new version 2.3.1, it should contain the typings. Let me know if they are not there. 

I've confirmed locally and with a fresh install.

**Comment by Beng89** [comment]
Much better, thank you!
