### ISSUE TITLE
Tile rotation

### ISSUE THREAD

**Issue by 0ArturkA** [excaliburjs/excalibur-tiled#18]
Why are the tile rotated in the "Tiled" editor, in the game do not save this rotation?
![image](https://user-images.githubusercontent.com/14136326/43648888-5a75f024-9744-11e8-9951-11b1880c476b.png)

**Comment by kamranayub** [comment]
The plug-in only makes it easier to import a tiled map structure, it's
still up to the developer to implement everything else on top of that
initial import. You would probably need to handle the rotation data and
apply it to the tile sprites. It may be possible for the extension to
handle this and many more features from Tiled but that was just not in
scope for the initial development.
