### ISSUE TITLE
Tile collision

### ISSUE THREAD

**Issue by Morb0** [excaliburjs/excalibur-tiled#19]
Collision set in "Tiled" edtior work in game?

**Comment by johnedvard** [comment]
Just to clarify. In the Tiled editor, we can create collision polygons as extra meta data for your tiles https://doc.mapeditor.org/en/stable/manual/editing-tilesets/#tile-collision-editor. Is it possible to use this information with collision detection using this plugin for Excalibur?

**Comment by kamranayub** [comment]
Not out-of-the-box.

If this data is part of the exported JSON that you load using this plugin, the data will be made available as part of `getData()`. But this plug-in at the moment does not do anything special with the data once it's loaded, that would be up to your game to implement.

If the data isn't part of the exported JSON, you could still load any other type of file using the [Generic resource](https://excaliburjs.com/docs/assets#generic-resources) and then you would handle it that way.

The `TileMap` in excalibur does not offer any polygon collision support directly, you would have to make your own mapping structure that translated the Tiled data into [ConvexPolygon collision shapes](https://excaliburjs.com/docs/physics#box-and-convexpolygon-shapes).

It would be an enhancement/feature to build the full map structure/tile map with all this information out-of-the-box for you. Definitely would be nice, but isn't offered yet.

**Comment by kamranayub** [comment]
Closing until sometime in the future where this may be offered.
