### ISSUE TITLE
Just doesn't work, as a browser script

### ISSUE THREAD

**Issue by mn113** [excaliburjs/excalibur-tiled#20]
I have Excalibur working on my page. But when I npm install and add this script in a script tag, it just doesn't load Extensions as a global or anywhere else, and I can't continue.

HTML
```
<script src="node_modules/excalibur/dist/excalibur.js"></script>
<script src="node_modules/@excaliburjs/excalibur-tiled/dist/excalibur-tiled.min.js"></script>
<script src="js/game.js"></script>
```
JS
```
var game = new ex.Engine({
width: 800,
height: 600
});

var map = new Extensions.Tiled.TiledResource("tiled/test.json");
```
Error in console
```
Uncaught ReferenceError: Extensions is not defined
```
Browser is Chrome 67. Versions are excalibur@0.18.0 and excalibur-tiled@2.3.0. My files are served from a local MAMP server (http://localhost:8888/...) and all the scripts show as being fetched (200 OK). Any hints? Is Webpack mandatory here?

**Comment by eonarheim** [comment]
@mn113  Webpack should not be required, we'll have a chance to look at this during our weekly meeting tonight

/cc @kamranayub

**Comment by eonarheim** [comment]
@mn113 I think something went wrong in the output, this seems to work as a workaround for now `new window["Extensions.Tiled"].default`

**Comment by kamranayub** [comment]
Probably due to how we export it globally. Will need to take a look at the
UMD webpack config area.

**Comment by eonarheim** [comment]
@mn113 I think we have a fix, webpack allows multipart library configuration which is what we want https://github.com/webpack/webpack/tree/master/examples/multi-part-library

/cc @kamranayub

**Comment by mn113** [comment]
The new PR seems to fix my problem.

Thanks for your quick work in responding to this @eonarheim.

**Comment by moonblade** [comment]
Could someone point me to the fix, I can see the pull request, but I can't find the branch its from.
I want to merge the pull request to my local copy.
Wasn't able to find it in eonarheim/excalibur-tiled
