### ISSUE TITLE
Spacing is being ignored

### ISSUE THREAD

**Issue by T00mm** [excaliburjs/excalibur-tiled#25]
As seen ![here](https://user-images.githubusercontent.com/3200970/47283897-78759900-d5e5-11e8-823a-fcc3d81d7d5b.png) is that spacing is being ignored even though it is described in the JSON file

```
{ "columns":8,
 "image":"tmw_desert_spacing.png",
 "imageheight":199,
 "imagewidth":265,
 "margin":0,
 "name":"tmw_desert_spacing",
 "spacing":1,
 "tilecount":48,
 "tiledversion":"1.2.0",
 "tileheight":32,
 "tilewidth":32,
 "type":"tileset",
 "version":1.2
}
```

**Comment by T00mm** [comment]
I've opened https://github.com/excaliburjs/Excalibur/issues/1058 so we can use the spacing setting.

**Comment by eonarheim** [comment]
@T00mm definitely something we want to add! Good find

**Comment by kamranayub** [comment]
Fixed in https://github.com/excaliburjs/Excalibur/issues/1058
