### ISSUE TITLE
Camera object is not always recognized

### ISSUE THREAD

**Issue by JumpLink** [excaliburjs/excalibur-tiled#254]
The camera is not recognized if the object layer in the tmx file is not the first object layer even if it is displayed in tiled in the first place.

### Steps to Reproduce

1. Create a object layer called "Collision" (It is important that this is created first)
2. Create a object layer called "Objects"
3. Insite the Objects layer create a camera object

Alternatively, the object layer `<objectgroup ...>...</objectgroup>` can also be inserted via text editor under another objectgroup tag, the issue always occurs when the objectgroup in the file is not in the first position

### Expected Result

The order of the object layer should not matter, the camera should always be recognized

### Actual Result

The camera is only recognized if the object layer in the file is above all other object layers.

### Environment

- browsers and versions: 
- operating system: 
- Tiled version: 
- Excalibur versions: 
- Tiled plugin versions: 
- (anything else that may be relevant) 
- Latest excalibur version in master and latest excalibur-tiled version in master. Browser does not matter

### Current Workaround

Change the order by hand in the file, it cannot be changed in Tiled although the position of the layer can be changed.

**Comment by eonarheim** [comment]
Good find! 

Agreed, the behavior _should_ scan each object layer with the excalibur custom prop.

![image](https://user-images.githubusercontent.com/612071/140241552-ff877779-1027-4e7d-b134-44e06db1b1ee.png)

This logic would need to be updated to do something better than the first object layer. Maybe first valid camera in all the object layers?
https://github.com/excaliburjs/excalibur-tiled/blob/f20fdf69d939ac0fce098b78a20e15bb9e3aa6cf/src/tiled-map-resource.ts#L229

**Comment by eonarheim** [comment]
@JumpLink I'm planning on cutting a release sometime this weekend with the latest fixes 🎉 thanks again for the report!
