### ISSUE TITLE
Add z-index property support for tile layer

### ISSUE THREAD

**Issue by JumpLink** [excaliburjs/excalibur-tiled#255]
### Context

It is uncomfortable to have to use tile objects every time you want a tile to appear above the hero, for example rooftops, trees, etc. There should be an easier way to set whole layer above the hero. This is also a common approach, for example in RPG Maker.

### Proposal

Add support for the ZIndex property as it is already available for Tile Objects.

**Comment by eonarheim** [comment]
@JumpLink I agree, z index support per layer would be great. 

Does this rely on a custom property for the layer? Something like this?

![image](https://user-images.githubusercontent.com/612071/140233631-b9ba320f-df02-4e97-b74a-050410e43792.png)

**Comment by eonarheim** [comment]
I'm 100% behind the z-indexed layers.

I propose we take a slightly different approach. Currently the Tiled plugin only creates one excalibur TileMap for all layers, it might make sense to create a TileMap for each layer instead. 

Creating an Actor for each z-index'd tiled layer tile instance might cause some performance overhead they come with a lot of extra features. TileMap is a more efficient data structure for drawing tiles than actors.

TileMap currently supports z-indexing for the whole map. Z-indexes could be assigned to each TileMap based on the Tiled editor order which would keep them consistent with what the game designer/level editor sees. 

```typescript
const tilemap = new ex.TileMap(...);
const tx = tilemap.get(ex.TransformComponent);
tx.z = 5;
```

Perhaps we could add an optionally configurable base z-index that increments with the Tiled layers? Maybe another optional constructor argument? 

```typescript
const options = { 
   layerZIndexBase: 0
}
// Options are optional
const tiledResource = new TiledMapResource("/assets/map.tmx", options);
// or
const tiledResource = new TiledMapResource("/assets/map.tmx");
```

To implement z-indexed layers:
1. Update the [parsing logic to create `TileMap` per Tiled editor and store the list of `TileMap`s with the right z](https://github.com/excaliburjs/excalibur-tiled/blob/cdbd13a65e47aa0dc2179efee0b9d54daefb6e7f/src/tiled-map-resource.ts#L448-L480)
2. Smallish breaking change: Update [`getTileMap` method](https://github.com/excaliburjs/excalibur-tiled/blob/cdbd13a65e47aa0dc2179efee0b9d54daefb6e7f/src/tiled-map-resource.ts#L486) accordingly to return the list of maps
3. Update the [`addTiledMapToScene`](https://github.com/excaliburjs/excalibur-tiled/blob/cdbd13a65e47aa0dc2179efee0b9d54daefb6e7f/src/tiled-map-resource.ts#L250) to add each TileMap to the Scene

**Comment by JumpLink** [comment]
@eonarheim sounds good. I'll see if I find the time to implement it that way.

To your screenshot: Yes, I would suggest that too.

What do you think of merging layers with the same zindex (or none) as is currently the case?  Then we would still have the performance advantage as currently.
