### ISSUE TITLE
How to indicate solid cells?

### ISSUE THREAD

**Issue by jweissman** [excaliburjs/excalibur-tiled#26]
I'm trying to understand how I might set cells to be `solid`, so that I can take advantage of collision detection [as hinted in the Excalibur docs](https://github.com/excaliburjs/Excalibur/blob/c3d02a53ed952dee56a277502a3e0a359e43cc2a/src/engine/Docs/TileMaps.md#collision-checks). 

I've tried creating custom properties on the Terrain objects; I have attempted this with both strings and booleans, with upper and lowercase `solid` (`Solid`).

I've tried setting a custom property (string/bool, upper/lowercase) on the Layer itself...

It seems like I might have to do some custom processing of the map data, but in order to do this it does seem like it could be useful if some of the properties set in Tiled might somehow make their way through to Excalibur's `TileMap` object?

Any guidance or advice anyone might have around this would really be helpful.

**Comment by jweissman** [comment]
Okay, I think I just put together that you've got access to most of the metadata in the raw `TiledResource`, as opposed to the `TileMap`, so you can do whatever custom processing you need there. (I'll be looking into this and will maybe try to report back a tiny recipe if I get it working.)

**Comment by eonarheim** [comment]
@jweissman Excellent! please do report back, we can include any recipes in our docs

**Comment by jweissman** [comment]
I ended up using something like this to detect whether a terrain has the `solid` prop and melding that into the downstream tilemap sprite: https://gist.github.com/jweissman/2793c47433e4bb50be046126c08a3db7
