### ISSUE TITLE
Tiled layer order should help decide zIndex

### ISSUE THREAD

**Issue by luttje** [excaliburjs/excalibur-tiled#285]
Right now the plugin **needs** us to specify a zindex property for individual inserted objects (and colliders). Tiled already provides it's own sorting system for layers. These layers are saved in order to a .tmx or .json file.

### Steps to Reproduce

1. Create a map in tiled with **at least 2 tile layers and one or more object layers**. (at least 2, because [tile layers start at z index -1](https://github.com/excaliburjs/excalibur-tiled/blob/02c122a11f3737928d9d19db3b3b77e6895c6196/src/tiled-map-resource.ts#L60))
2. **Sort the layers** so the objects are above the tile layers
3. Create an **inserted object (or collider)** in one of the top object layers.
_For demonstration purposes I've positioned a fire (child of AnimatedFire layer) on top of the fireplace (child of Overlay1 layer):_
![image](https://user-images.githubusercontent.com/2738114/148646897-15e34fd9-fb42-4e1a-8436-0e878261a4d6.png)
3. Load the map in the way described in the README

### Expected Result
I would expect the Tiled layer sorting to help this plugin decide the z index for the actors. [Currently for tiles a z index is automatically decided](https://github.com/excaliburjs/excalibur-tiled/blob/02c122a11f3737928d9d19db3b3b77e6895c6196/src/tiled-map-resource.ts#L435), but this is not the actual order as the layer occurs in the map file. For [actors](https://github.com/excaliburjs/excalibur-tiled/blob/02c122a11f3737928d9d19db3b3b77e6895c6196/src/tiled-map-resource.ts#L185) and [colliders](https://github.com/excaliburjs/excalibur-tiled/blob/02c122a11f3737928d9d19db3b3b77e6895c6196/src/tiled-map-resource.ts#L124) an absolute zindex (specified in the property of the object) is needed.

### Actual Result

The z index of the actor is unchanged (therefor 0) because no property is set. This causes the tiles to overlap the actor. [(The tiles have their z index automatically decided starting from -1)](https://github.com/excaliburjs/excalibur-tiled/blob/02c122a11f3737928d9d19db3b3b77e6895c6196/src/tiled-map-resource.ts#L435)
![image](https://user-images.githubusercontent.com/2738114/148646929-f2979a7f-4b99-4228-b9a7-5dd7c44cf819.png)

### Current Workaround

Manually set a zindex property on each object and tile layers (this is how the examples in `./examples` avoid this problem)

### Proposed fix
Sadly I'm not motivated enough to create a PR, though I hope I can still aid you with a (hopefully) clear bug report and proposed fix:

* The .tmx file contains all tile and object layers in order
* [This code would require a substantial change](https://github.com/excaliburjs/excalibur-tiled/blob/02c122a11f3737928d9d19db3b3b77e6895c6196/src/tiled-map.ts#L96)
* The map file would have to be parsed preserving the order of the nodes
* The layer's default zIndex would be it's offset from the first layer node

### Should this be fixed?
In my opinion: eventually yes. Because:
* The sorting is respected by the Tiled map editor. 
* The behavior intuitive.
* When I didn't see my objects in-game it took me a good couple minutes to realize that it was not something I was doing wrong.
* With more objects comes more manual management of z indexes, which can be tedious

However looking at the amount of work that is required to fix this, the workaround seems a viable alternative for now.

I really hope this helps you all. 

Thanks for your time and effort!

**Comment by eonarheim** [comment]
100% agree, I would expect consistent z-index/sorting behavior between Tiled and the plugin.

I think you're on track with the proposed fix 👍

**Comment by eonarheim** [comment]
I think I might also be able to squeeze this one into the next release as well 🤞

**Comment by luttje** [comment]
Whether it makes the release or not: thanks a lot for your efforts!
