### ISSUE TITLE
Tilesets based on collection of images

### ISSUE THREAD

**Issue by ewal** [excaliburjs/excalibur-tiled#382]
Tiled editor v1.8.6
excalibur-tiled v0.26.2
excalibur v0.26.0

Been trying to use a tileset that is based on a "Collection of images" without luck.
Should it be possible to use these types of tilesets, and if not, any plans to add support for them?

In my case I have a set of standalone looping background images that I wish to have in a single tileset. I can use a "Tileset image" tileset for each file but it would just be nice to be able to collect them in a single file :)

![image](https://user-images.githubusercontent.com/676873/175791055-54168b92-f8f6-4f0b-aa27-645e7b2091a3.png)

**Comment by eonarheim** [comment]
@ewal I don't think it's currently possible, but it definitely should be part of the plugin. I support this 👍 

The workaround right now would be to merge the images into 1 unfortunately.

**Comment by ewal** [comment]
Thanks :+1:

**Comment by ewal** [comment]
Saw that you referenced the issue just after I closed it so I'll reopen it.

**Comment by eonarheim** [comment]
@ewal Thanks for bringing this to our attention!

Closed in #383

**Comment by ewal** [comment]
That was fast! Thank you for the quick respond and action. :muscle:
