### ISSUE TITLE
Property `type`renamed to `class` in the latest version of Tiled (1.9.0)

### ISSUE THREAD

**Issue by ewal** [excaliburjs/excalibur-tiled#384]
Just a fyi; installed the latest update and noticed this breaking change:
https://doc.mapeditor.org/en/stable/reference/tmx-changelog/#tiled-1-9

**Comment by eonarheim** [comment]
@ewal Thanks for the heads up! I'll make sure the latest plugin works with Tiled 1.9 👍

**Comment by JumpLink** [comment]
@eonarheim This change was reverted in Tiled 1.10, see https://www.mapeditor.org/2023/03/10/tiled-1-10-released.html

So this should also be revered here
