### ISSUE TITLE
Layers are sometimes not rendered

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/excalibur-tiled#387]
Sometimes a layer (or layers) in the tilemap will not get rendered when scene is initialized. It's seemingly completely random. I've got a video of it happening below, but it only happened twice in 1.5 minutes of me refreshing the page & clicking play:

https://user-images.githubusercontent.com/8703090/177651114-e46bf4f3-6df9-4e93-9813-da08840c2dea.mp4

I first noticed this in a larger project with multiple scenes and it was happening a bit more frequently. It seemed to be more likely to happen if I left the tab open for a long time between refreshes (i.e page reloads while I was making changes in my code editor before flipping back to the browser), but I have not been able to track down any specific cause.

There are no errors or warnings in console and the layer's image shows as loaded in the network tab, so as far as I can tell the image resource is properly loaded.

### Steps to Reproduce

I've made a repro project here: https://github.com/mattjennings/excalibur-tiled-layer-bug

- `npm install` & `npm run dev`
- Keep refreshing browser and playing game until it (hopefully) happens.

### Expected Result
All layers should render

### Actual Result
Sometimes layers are missing

### Environment

- browsers and versions: Chrome 103.0.5060.53, Firefox 102.0. I have not been able to reproduce in Safari, but I have in another Webkit-based browser, Orion (WebKit version 614.1.20)
- operating system: macOS 12.4
- Tiled version: 1.8.4
- Excalibur versions: 0.26
- Tiled plugin versions: 0.26.2

I had noticed #381 and hoped it would possibly be related to what I was seeing, so I tried a local build from source shortly after iti was merged but sadly it still occurred.

### Current Workaround
None

**Comment by mattjennings** [comment]
It's possible this only happens for tilemaps with external tilesets. If I remember back to when I first noticed this, it was when I switched from embedded to external tilesets. 

I'm re-trying my repro now with embedded tilesets and I'm not seeing it happen... so I'll mention it here if I see otherwise.

**Comment by eonarheim** [comment]
@mattjennings thanks for the issue! This is definitely bizarre

I think your instinct that external tilesets might be related is on the mark.

If so, this recent PR might have fixed the issue https://github.com/excaliburjs/excalibur-tiled/pull/380 I'll double check locally. 

If the tileset ever loaded out of order relative to their first gid it might present like this because it would select the wrong tileset for a tile potentially.

**Comment by eonarheim** [comment]
I can reproduce the issue locally pretty consistently by swapping the order of the tilesets in the tmx

<img width="385" alt="image" src="https://user-images.githubusercontent.com/612071/177662590-d9801465-86f0-4931-96a9-fa48d57a23ae.png">

Dropping my local build of `@excaliburjs/plugin-tiled` seems to solve the issue? I'm going to refresh a few more times before I declare victory. I'm planning on releasing excalibur and plugins this week so a new version should theoretically fix the external tileset issue.

**Comment by mattjennings** [comment]
Ah! Perhaps I didn't have it properly symlinked when I tried a local build... that would be embarassing 😬. If so, my apologies but I'm glad to see that it could already be fixed!

**Comment by eonarheim** [comment]
I've noticed that vite pretty aggressively caches npm dependencies, I've had to manually clear the cache to see changes.

I couldn't get `npm link` to work with vite when testing locally and wound up copying the built files into the project. 

I literally just found this article https://dev.to/hontas/using-vite-with-linked-dependencies-37n7 which suggests `optimizeDeps.exclude` as a way to do linked deps, but this doesn't seem to work for me either :(

**Comment by mattjennings** [comment]
Mm yes, I have many (**many**) hours fiddling around with vite's `optimizeDeps` and its caching of node_modules... that is probably what happened there and I hadn't realized.

Although I think that article has it backwards, or their scenario was unique, because `optimizeDeps.include` is what you're supposed to use for linked modules 😅 https://vitejs.dev/config/#optimizedeps-include (and that will put them in the vite cache, so if it changes, you gotta nuke `node_modules/.vite`)

**Comment by mattjennings** [comment]
Unfortunately I seem to be seeing this still (albeit less frequently - unless it's placebo). I haven't investigated further yet, just wanted to note that here for the meantime.

**Comment by eonarheim** [comment]
@mattjennings I'll look into it. Same reproduction repo that you posted originally in this issue?

If you catch the not loading again, I'd be curious about the order of the resources loaded in your network tab. Maybe there is still and order of operations issue?

**Comment by mattjennings** [comment]
I haven't tried it with the repro again yet, just have seen it in my own projects. Don't worry about looking into it until I can repro it again as I feel like it might be even more random than before, but I'll keep an eye on the resource load order when I see it next!
