### ISSUE TITLE
Tile custom colliders on isometric map causes error on load

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/excalibur-tiled#391]
I'm not sure if tile custom colliders are officially supported, but an error is thrown when trying to use them.

```
Log.ts:173 [Error] :  Error loading resources, things may not behave properly TypeError: Cannot read properties of undefined (reading 'split')
    at B.getCollidersForGid (tiled-map-resource.ts:513:35)
    at B._createTileMap (tiled-map-resource.ts:664:45)
    at tiled-map-resource.ts:412:18
```

It seems the polygon data structure is not what it expects:

<img width="455" alt="CleanShot 2022-07-21 at 23 21 28@2x" src="https://user-images.githubusercontent.com/8703090/180361885-87b0651c-a77b-4cd0-9d6d-29a8c04d0509.png">

(inspecting `polygon.polygon`)
### Steps to Reproduce

See repro: https://github.com/mattjennings/excalibur-iso-tiled-collider-bug

```
npm install
npm run dev
```

I've added both an isometric and orthogonal tilemap that uses the same tileset. When loading the isometric, the above error occurs on load. However, the orthogonal map does not cause the error, so the polygon data must be different in isometric vs orthogonal?

### Expected Result

Isometric custom tile colliders to be loaded

### Actual Result
An error is thrown

### Environment

- browsers and versions: Chrome 103
- operating system: macOS 12.4
- Tiled version: 1.9.0
- Excalibur versions: 0.27.0
- Tiled plugin versions: 0.27.0
- (anything else that may be relevant) 

### Current Workaround
None

**Comment by eonarheim** [comment]
@mattjennings Thanks for the bug! 

I bet this a bug in the TSX vs TSJ parsing. The XML version stores the points in an odd string representation that needs parsing. It appears the TSJ is far more convenient. Should be a quick fix to support the TSJ hopefully🤞 

I've had a few of these types of bugs, I might spend some after fixing this to refactor the tiled parsing to be more robust.

**Comment by eonarheim** [comment]
I have something that mostly works, needs more testing. Vite really resists npm link!

<img width="625" alt="image" src="https://user-images.githubusercontent.com/612071/180478110-e4979e16-1ad2-4d57-9df5-1a67bf5b6932.png">

**Comment by mattjennings** [comment]
@eonarheim I spent some time trying to get `@excaliburjs/plugin-tiled` propertly symlinking with vite myself and the following `vite.config.js` is what worked for me:

```js
import { defineConfig } from 'vite'

export default defineConfig({
  optimizeDeps: {    
    force: true, // vite 3.0.0 feature, busts node_modules prebundle cache
  },
  resolve: {
    preserveSymlinks: true,
    dedupe: ['excalibur']
  }
})
```

However I use `pnpm` to both install and link my packages (`pnpm link path/to/excalibur-tiled`), so possibly there's some differences there with `npm link`, but this is what finally made it work reliably for me
