### ISSUE TITLE
Global Class Identification

### ISSUE THREAD

**Issue by cemalgnlts** [excaliburjs/excalibur-tiled#451]
Hi,

### Context
In order not to name the decors for the game every time, I gave the Decor `Class` from the tile options:
![Screenshot 2023-08-06 10 57 08](https://github.com/excaliburjs/excalibur-tiled/assets/45357531/738cccb3-651a-49fa-b6aa-dd7537b678b8)

Then when I add it to my map, it automatically comes up with the same `Class` name:
![Screenshot 2023-08-06 10 57 39](https://github.com/excaliburjs/excalibur-tiled/assets/45357531/b17d7244-b203-4051-934c-a0487e82ee6a)

Here's how it looks in the output file:
```xml
<tileset firstgid="42" name="Decors" tilewidth="80" tileheight="61" tilecount="8" columns="0">
  <grid orientation="orthogonal" width="1" height="1"/>

  <!-- The class name is given as type instead of class. -->
  <tile id="0" type="Decor">
   <image width="42" height="44" source="../decors/barrel.png"/>
  </tile>

  <!-- The class name is given as type instead of class. -->
  <tile id="1" type="Decor">
   <image width="16" height="21" source="../decors/blue_bottle.png"/>
  </tile>
</tileset>
```

### Proposal
There are already functions like `getObjectByType` & `getObjectByClass` in the documentation, but they don't care about global class naming.

**Comment by eonarheim** [comment]
Hi @cemalgnlts thanks for the issue!

I totally agree, the existing functions should respect the global class
