### ISSUE TITLE
Doesn't seem to be compatible with ExcaliburJs 0.7.1, fails when loading resource

### ISSUE THREAD

**Issue by nicanaca0** [excaliburjs/excalibur-tiled#7]
I'm trying to follow the the example in the README to load my json file but it fails when the loader tries to loads the resource and the app gets stuck on the progress bar screen with this error shown in the console.
`TypeError: Argument 1 is not valid for any of the 2-argument overloads of URL.createObjectURL.`

My code looks like this;
`// Create a new TiledResource loadable`
`var map = new ex.Extensions.Tiled.TiledResource("/assets/levels/room1.json");`
`// Create a loader and reference the map`
`loader.addResource(map);`

My json file was generated using Tiled Map Editor Version 0.17.0 with the CSV setting and Exported As .json

I'm not 100% about how the `"image":"..\/tilemap.png",` will work in the .json file so I copied the file into every level of my directory structure just to make sure it isn't failing because it cannot find the `tilemap.png` file.

Note: I downloaded the files manually as bower is set to only support `"~0.6.0"`

**Comment by kamranayub** [comment]
Let me try testing/updating to 0.7.1 and seeing what's up. The resources changed a bit, which could have caused a regression.

**Comment by kamranayub** [comment]
Updated to 1.2, which now supports 0.7.1. Thanks for reporting!
