### ISSUE TITLE
error TS2304: Cannot find name 'Extensions'.

### ISSUE THREAD

**Issue by wrlell** [excaliburjs/excalibur-tiled#71]
how the fuck are we supposed to use this garbage when there are no typings for 'Extensions' anywhere?? I've included all the typings present but theres nothing for 'Extensions'.....

**Comment by wrlell** [comment]
Not even with webpack it works since there's no such module named 'excalibur-tiled' and when fixed to use '@excaliburjs/excalibur-tiled' it fails with a 'Module has no default export'........ exact same code as in the readme....

**Comment by eonarheim** [comment]
@wrlell 

Thank you for bringing this issue to our attention. We’re sorry about the frustration; the Readme is not very clear about how to use excalibur-tiled in a project with TypeScript.

We have an interim example posted in CodeSandbox which shows how to load a Tiled map JSON file: https://codesandbox.io/s/falling-lake-4f83x?fontsize=14. This example is using Parcel.js, which requires a bit less configuration than Webpack. 

The recommended way to use Excalibur and Excalibur Tiled is with ES2015 modules, which Parcel and Webpack both support. 

A new issue has been opened to update the documentation and provide better examples: https://github.com/excaliburjs/excalibur-tiled/issues/72

In the future, please be kinder in your choice of language when opening issues. Our [code of conduct](https://github.com/excaliburjs/Excalibur/blob/master/.github/CODE_OF_CONDUCT.md) outlines the expectations for everyone who participates and contributes in all ExcaliburJS projects.

_the ExcaliburJS team_

**Comment by eonarheim** [comment]
Closing, these issues are the follow up
* https://github.com/excaliburjs/excalibur-tiled/issues/72
* https://github.com/excaliburjs/excalibur-tiled/issues/74
