### ISSUE TITLE
Documentation needs updating to include better direction and examples

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/excalibur-tiled#72]
### Context
`excalibur-tiled` is not straightforward to include in an Excalibur project. The readme should provide more clarity and direction on how to use `excalibur-tiled`.

### Proposal
* [x] Update the readme with more information around including and building `excalibur-tiled` into a project
* [x] Create an example and link to it in the readme

**Comment by kamranayub** [comment]
Done. Linked to Parcel example in CodeSandbox and your example webpack branch, also created #74 to make it easier to use in webpack without so much configuration.
