### ISSUE TITLE
Work with Tiled collision property

### ISSUE THREAD

**Issue by RALMAZ** [excaliburjs/excalibur-tiled#86]
We really need this feature, without this I have waste time for 40000 tiles collision by create invisible Actor`s

**Comment by eonarheim** [comment]
@RALMAZ Thanks for posting an issue, the collision support is not super robust for excalibur TileMaps at the moment, we'll prioritize this improving collision support in TileMaps w/ excalibur-tiled and get this on our roadmap for an upcoming release. 

Does manually setting cells to `.solid = true` work for you at the moment? https://github.com/excaliburjs/Excalibur/blob/master/src/engine/TileMap.ts#L303 

@kamranayub Any pointers on how to proceed?

**Comment by DaVince** [comment]
Is there any collision support at all yet in excalibur-tiled? I've looked at the source and haven't found much. I'd like to at least implement a basic version that works with the current way in which TileMaps handle collision.

Just a quick check to see whether a cell's tile has property "type":"collision" should be sufficient to make it work. (The "collision" type is a default option in Tiled.)

**Comment by DaVince** [comment]
For anyone who wants basic collisions _now_, I made a little workaround that doesn't require you to edit excalibur-tiled. It's pretty hacky but it works.

Note that it generates collision from ALL layers, so you might want to have a dedicated tile and layer that mark the "collision" property.

```ts
this.levelResource = new TiledResource("some-map-file.json");

// Run this in scene onInitialize() but after you have successfully loaded the Tiled map.
this.engine.load(this.levelResource).then(() => {

  // Make a list of all solid tiles in tilesets
  let tilesetTerrain = [];
  for (let _set in this.levelResource.data.tilesets) {
    const tiles = this.levelResource.data.tilesets[_set].tiles;
    for (let _tile in tiles) {
      if (tiles[_tile]['type'] === 'collision') {
        tilesetTerrain[tiles[_tile]['id']] = true;
      }
    }
  }

  // Add tilemap
  this.levelTileMap = this.levelResource.getTileMap();
  this.addTileMap(this.levelTileMap);

  // Add collision to tiles
  this.levelTileMap.data.forEach(cell => {
    if (cell.sprites[0]) {
      if (tilesetTerrain[cell.sprites[0].spriteId] === true) {
        cell.solid = true;
      }
    }
  });
});
```

Note that extra logic may be required to make it play well with the physics system.
