### ISSUE TITLE
Adding Actor to Scene causing crash

### ISSUE THREAD

**Issue by bleeinc** [excaliburjs/excalibur-tiled#87]
### Steps to Reproduce

https://codesandbox.io/s/excalibur-tiled-example-q8twd

Starting with a very basic project (I forked the tile map example) if you add an Actor to a scene with a tilemap the game crashes (technically still runs, there are no errors but cpu pegs at 100% and window crashes)

### Expected Result
You can add actors to scenes with tilemaps

### Actual Result
Game Crashes

### Environment

- browsers and versions: Version 78.0.3904.108 (Official Build) (64-bit)
- operating system: Windows 10
- Excalibur versions: Latest 0.23.0

**Comment by DaVince** [comment]
I had the same issue, it seems it wasn't Tiled-specific Working on a fix, see https://github.com/excaliburjs/Excalibur/issues/1418 🙂

**Comment by eonarheim** [comment]
Agreed thanks for spotting, fixed in excaliburjs/Excalibur#1418
